### ISSUE TITLE
12-bit variable type in arduino

### ISSUE THREAD

**Issue by NoNamedCat** [jcrona/tamatool#2]
Arduino don't have a 12 bit variable type. So when i try to import the rom.h file it shows an error for this variable type. Do you have some suggestion to port this to the arduino? I think that porting this emulator to the arduino are a great idea!
Tks a lot for your efforts!

**Comment by jcrona** [comment]
Would be cool to see TamaLIB working on an Arduino ! Take a look at the [MCUGotchi](https://github.com/jcrona/mcugotchi) project, this will be a good starting point for you. Regarding the 12-bit type, you need to provide the actual C type to use for that in the **hal_types.h** file. Look at the [TamaLIB](https://github.com/jcrona/tamalib) repository for more information regarding how to use it on your project.
