### ISSUE TITLE
Discipline: Attempt to write at invalid memory address

### ISSUE THREAD

**Issue by Almarch** [jcrona/tamatool#4]
Hello, congratulations for this fantastic project. I gave it a try in both a windows and a linux environments ; and it works smoothly, up to an error. Indeed, when the creatures needs discipline, and that it is provided, then consulting the discipline gauge leads to an error (that is printed in the bash):

Write 0xA to invalid memory address 0x2C6 - PC = 0x0879
Write 0x5 to invalid memory address 0x2C7 - PC = 0x0879
Write 0xA to invalid memory address 0x2CA - PC = 0x0879
Write 0x5 to invalid memory address 0x2CB - PC = 0x0879
Write 0xA to invalid memory address 0x2CE - PC = 0x0879
Write 0x5 to invalid memory address 0x2CF - PC = 0x0879
Write 0xA to invalid memory address 0x2D2 - PC = 0x0879
Write 0x5 to invalid memory address 0x2D3 - PC = 0x0879
Write 0xA to invalid memory address 0x2D6 - PC = 0x0879
Write 0x5 to invalid memory address 0x2D7 - PC = 0x0879
Write 0xA to invalid memory address 0x2DA - PC = 0x0879
Write 0x5 to invalid memory address 0x2DB - PC = 0x0879
Write 0xA to invalid memory address 0x2DE - PC = 0x0879
Write 0x5 to invalid memory address 0x2DF - PC = 0x0879

The discipline does not increase with correction (which it should). The error is reproducible with both the windows and the linux versions. I e-mailed you a reproducible example, hoping that it helps. Unfortunately, I have no way to identify if the issue comes from tamatool ; from tamalib ; or from the ROM itself ; this being beyond my capabilities. Thanks again for this great work, Best regards.

**Comment by jcrona** [comment]
Thanks for this report ! Did you reproduce this issue with a fresh build of the master branch of TamaTool, or was it with the release binaries ?

**Comment by Almarch** [comment]
I've used the release binary for the windows test ; and I've built it from master for the linux test.

I tested the windows release binary on both a native windows OS and using wine from a Lubuntu OS ; and I've built and tested the linux version from a Lubuntu OS.

**Comment by jcrona** [comment]
I did reproduce the issue, and it was a bug in TamaLIB (https://github.com/jcrona/tamalib/commit/08f9371f606da7195d4be19afcb072e17b6fc202).

Thanks a lot for your example !

**Comment by Almarch** [comment]
It works perfectly on my end as well. Thank you, that's very cool !

**Comment by superblobster** [comment]
It appears this bug was never fully fixed.

**Comment by Almarch** [comment]
The issue I faced has well been fixed, however the release has never been updated with the fix. Have you tried compiling it yourself ?

**Comment by superblobster** [comment]
> The issue I faced has well been fixed, however the release has never been updated with the fix. Have you tried compiling it yourself ?

Why was it never updated??
I assumed it to be the latest version.
I do not know how to compile it myself.

Edit: OK, I kinda lied. I was just lazy and didn't feel like installing Linux. But I've now made a Ubuntu machine in VMWare and the instructions were surprisingly simple.
Since the proprietor is unwilling or unable to release an updated build, I'm uploading my compiled Windows build here for anyone who finds this post:
https://mega.nz/file/m0gg2L5Z#o7_8qoUzCB0hcV8kTxerQ63sa-BmVJpzSx3P8m3TAz0
