### ISSUE TITLE
Windows version: computer score when playing

### ISSUE THREAD

**Issue by Almarch** [jcrona/tamatool#5]
When playing with the creature, the score is delivered as "X vs Y". X is the creature score, ranging from 0 to 5, and Y the opposite score, that should be 5 minus X. In the windows version only, Y is always returned as 5. This issue is inexistant in the linux version, where Y is properly defined as the difference between 5 and X. Windows and linux tests used the same ROM.

**Comment by Almarch** [comment]
Sorry, I just noticed the issue has already been raised. I'm not familiar with github yet.

However, it's noteworthy that the same ROM yields different outputs when using tamatool in a Windows or a Linux environment.

**Comment by jcrona** [comment]
Hi, this issue should be fixed in TamaLIB already. However, there has been no TamaTool release including the fix yet. Did you reproduce the issue with your own Windows build of the master branch ?

**Comment by Almarch** [comment]
Hi, thanks for your feedback. I will build it and test and let you know :-)

**Comment by Almarch** [comment]
The issue is indeed fixed when building the windows version from master. It only affects the release binary. Thank you !

**Comment by jcrona** [comment]
Good !
